// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc4546.Shockwave2018.subsystems;

import org.usfirst.frc4546.Shockwave2018.RobotMap;
import org.usfirst.frc4546.Shockwave2018.commands.*;
import edu.wpi.first.wpilibj.command.Subsystem;
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.Spark;
import edu.wpi.first.wpilibj.SpeedController;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS


/**
 *
 */
public class ControlSub extends Subsystem {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    private final SpeedController speedController1 = RobotMap.controlSubSpeedController1;
    private final SpeedController speedController2 = RobotMap.controlSubSpeedController2;
    private final SpeedController speedController3 = RobotMap.controlSubSpeedController3;
    private final SpeedController speedController4 = RobotMap.controlSubSpeedController4;
    private final SpeedController speedController5 = RobotMap.controlSubSpeedController5;
    private final SpeedController speedController6 = RobotMap.controlSubSpeedController6;
    private final SpeedController speedController7 = RobotMap.controlSubSpeedController7;
    private final SpeedController speedController8 = RobotMap.controlSubSpeedController8;
    private final SpeedController speedController9 = RobotMap.controlSubSpeedController9;
    private final SpeedController speedController10 = RobotMap.controlSubSpeedController10;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    
    @Override
    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        // Set the default command for a subsystem here.
        // setDefaultCommand(new MySpecialCommand());
    }

    @Override
    public void periodic() {
        // Put code here to be run every loop

    }

    // Put methods for controlling this subsystem
    // here. Call these from Commands.

}

