// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc4546.Shockwave2018.subsystems;

import org.usfirst.frc4546.Shockwave2018.RobotMap;
import org.usfirst.frc4546.Shockwave2018.commands.*;
import org.usfirst.frc4546.Shockwave2018.OI;
import edu.wpi.first.wpilibj.command.Subsystem;
import edu.wpi.first.wpilibj.GenericHID.Hand;
import edu.wpi.first.wpilibj.Spark;
import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.Talon;
import edu.wpi.first.wpilibj.VictorSP;
import edu.wpi.first.wpilibj.XboxController;



/**
 *
 */
public class ControlSub extends Subsystem {
    /**private SpeedController speedController1 = RobotMap.controlSubSpeedController1;
    private static final int kMotorPort1 = 0;
    private SpeedController speedController2 = RobotMap.controlSubSpeedController2;
    private static final int kMotorPort2 = 1;
    private SpeedController speedController3 = RobotMap.controlSubSpeedController3;
    private static final int kMotorPort3 = 2;
    private SpeedController speedController4 = RobotMap.controlSubSpeedController4;
    private static final int kMotorPort4 = 3;
    private SpeedController speedController5 = RobotMap.controlSubSpeedController5;
    private static final int kIntakePort5 = 4;
    private SpeedController speedController6 = RobotMap.controlSubSpeedController6;
    private static final int kIntakePort6 = 5;
    //private SpeedController speedController7 = RobotMap.controlSubSpeedController7;
    //private static final int kMotorPort7 = 6;
    //private SpeedController speedController8 = RobotMap.controlSubSpeedController8;
    //private static final int kMotorPort8 = 7;
    //private SpeedController speedController9 = RobotMap.controlSubSpeedController9;
    //private static final int kMotorPort9 = 8;
    //private SpeedController speedController10 = RobotMap.controlSubSpeedController10;
    //private static final int kMotorPort10 = 9;
    private XboxController Xbox1 = OI.Xbox1;
    private XboxController Xbox2 = OI.Xbox2;
    //private XboxController Xbox2 = OI.Xbox2;
    
    private double speedF1 = .5;
    private double speedR1 = -.5;
    
    private double speedF2 = .5;
    private double speedR2 = -.5;
    
    private double speedF3 = .5;
    private double speedR3 = -.5;
    
    private double speedF4 = .5;
    private double speedR4 = -.5;*/

    @Override
    public void initDefaultCommand() {
    	/**speedController1 = new Talon(kMotorPort1);
    	speedController2 = new Talon(kMotorPort2);
    	speedController3 = new Talon(kMotorPort3);
    	speedController4 = new Talon(kMotorPort4);
    	speedController1.setInverted(true);
    	speedController2.setInverted(true);
    	speedController5 = new VictorSP(kIntakePort5);
    	speedController6 = new VictorSP(kIntakePort6);
    	speedController5.setInverted(true);
    	Xbox2 = new XboxController(1);  
        Xbox1 = new XboxController(0);*/
    }

    @Override
    public void periodic() {
        // Put code here to be run every loop
    	/**if(Xbox1.getY(Hand.kLeft)<.1 && Xbox1.getY(Hand.kLeft)>-.1){
    		speedController1.set(0);
    		speedController2.set(0);
    	}else if(Xbox1.getY(Hand.kLeft)>=.1){
    		speedController1.set(Xbox1.getY(Hand.kLeft)*speedF1);
    		speedController2.set(Xbox1.getY(Hand.kLeft)*speedF2);
    	}else if(Xbox1.getY(Hand.kLeft)<=-.1){
    		speedController1.set(Xbox1.getY(Hand.kLeft)*speedR1);
    		speedController2.set(Xbox1.getY(Hand.kLeft)*speedR2);
    	}

    	if(Xbox1.getY(Hand.kRight)<.1 && Xbox1.getY(Hand.kRight)>-.1){
    		speedController3.set(0);
    		speedController4.set(0);
    	}else if(Xbox1.getY(Hand.kRight)>=.1){
    		speedController3.set(Xbox1.getY(Hand.kRight)*speedF3);
    		speedController4.set(Xbox1.getY(Hand.kRight)*speedF4);
    	}else if(Xbox1.getY(Hand.kRight)<=-.1){
    		speedController3.set(Xbox1.getY(Hand.kRight)*speedR3);
    		speedController4.set(Xbox1.getY(Hand.kRight)*speedR4);
    	}*/
    }

    // Put methods for controlling this subsystem
    // here. Call these from Commands.

}

