// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc4546.Shockwave2018.subsystems;


import edu.wpi.first.wpilibj.Timer;
import org.usfirst.frc4546.Shockwave2018.RobotMap;
import org.usfirst.frc4546.Shockwave2018.commands.*;
import edu.wpi.first.wpilibj.command.Subsystem;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.PowerDistributionPanel;

   


/**
 *
 */
public class PDPSub extends Subsystem {
	
	private static final int kPDP = 0;
	private PowerDistributionPanel m_PDP;
	
	
	

    private final PowerDistributionPanel powerDistributionPanel = RobotMap.pDPSubPowerDistributionPanel;


    @Override
    public void initDefaultCommand() {
    	
    	m_PDP = new PowerDistributionPanel(kPDP);
    	
        // Set the default command for a subsystem here.
        // setDefaultCommand(new MySpecialCommand());
    }

    @Override
    public void periodic() {
        // Put code here to be run every loop
    	
    	SmartDashboard.putNumber("Current", m_PDP.getCurrent(kPDP));
    	SmartDashboard.putNumber("Total Power", m_PDP.getTotalPower());
    	SmartDashboard.putNumber("Total", (m_PDP.getTotalPower())*(Timer.getMatchTime()));
    	
    }

    // Put methods for controlling this subsystem
    // here. Call these from Commands.

}

